#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "running pre-commit hook"

if [ -f subssh/version.txt ]
then
    date +"%Y%m%d-%H%M%S-hgdev" > subssh/version.txt
else
    echo subssh/version.txt does not exist!
    exit 1
fi 
