#!/usr/bin/env python

import sys
import os

try:
    sys.path.insert(0, os.environ['SUBSSHPYTHONPATH'])
except KeyError:
    pass

from subssh import dispatcher


if __name__ == "__main__":
    sys.exit(dispatcher.dispatch() or 0)
